// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/common.proto

package hermesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason hermes 业务错误码，通过 google.rpc.ErrorInfo.reason 传递
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// NotFound 系列 → gRPC NOT_FOUND
	ErrorReason_DOMAIN_NOT_FOUND            ErrorReason = 1
	ErrorReason_APPLICATION_NOT_FOUND       ErrorReason = 2
	ErrorReason_SERVICE_NOT_FOUND           ErrorReason = 3
	ErrorReason_USER_NOT_FOUND              ErrorReason = 4
	ErrorReason_IDENTITY_NOT_FOUND          ErrorReason = 5
	ErrorReason_CREDENTIAL_NOT_FOUND        ErrorReason = 6
	ErrorReason_RELATIONSHIP_NOT_FOUND      ErrorReason = 7
	ErrorReason_GROUP_NOT_FOUND             ErrorReason = 8
	ErrorReason_KEY_NOT_FOUND               ErrorReason = 9
	ErrorReason_CHALLENGE_SETTING_NOT_FOUND ErrorReason = 10
	// AlreadyExists 系列 → gRPC ALREADY_EXISTS
	ErrorReason_APPLICATION_ALREADY_EXISTS ErrorReason = 100
	ErrorReason_CREDENTIAL_ALREADY_EXISTS  ErrorReason = 101
	ErrorReason_IDENTITY_ALREADY_EXISTS    ErrorReason = 102
	ErrorReason_TOTP_ALREADY_BOUND         ErrorReason = 103
	// FailedPrecondition 系列 → gRPC FAILED_PRECONDITION
	ErrorReason_PASSWORD_INCORRECT     ErrorReason = 200
	ErrorReason_OTP_INVALID            ErrorReason = 201
	ErrorReason_IDP_NOT_ALLOWED        ErrorReason = 202
	ErrorReason_USER_DISABLED          ErrorReason = 203
	ErrorReason_SIGN_COUNT_ANOMALY     ErrorReason = 204
	ErrorReason_TOTP_NOT_BOUND         ErrorReason = 205
	ErrorReason_CREDENTIAL_NOT_ENABLED ErrorReason = 206
	// PermissionDenied 系列 → gRPC PERMISSION_DENIED
	ErrorReason_APP_SERVICE_ACCESS_DENIED ErrorReason = 300
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "ERROR_REASON_UNSPECIFIED",
		1:   "DOMAIN_NOT_FOUND",
		2:   "APPLICATION_NOT_FOUND",
		3:   "SERVICE_NOT_FOUND",
		4:   "USER_NOT_FOUND",
		5:   "IDENTITY_NOT_FOUND",
		6:   "CREDENTIAL_NOT_FOUND",
		7:   "RELATIONSHIP_NOT_FOUND",
		8:   "GROUP_NOT_FOUND",
		9:   "KEY_NOT_FOUND",
		10:  "CHALLENGE_SETTING_NOT_FOUND",
		100: "APPLICATION_ALREADY_EXISTS",
		101: "CREDENTIAL_ALREADY_EXISTS",
		102: "IDENTITY_ALREADY_EXISTS",
		103: "TOTP_ALREADY_BOUND",
		200: "PASSWORD_INCORRECT",
		201: "OTP_INVALID",
		202: "IDP_NOT_ALLOWED",
		203: "USER_DISABLED",
		204: "SIGN_COUNT_ANOMALY",
		205: "TOTP_NOT_BOUND",
		206: "CREDENTIAL_NOT_ENABLED",
		300: "APP_SERVICE_ACCESS_DENIED",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":    0,
		"DOMAIN_NOT_FOUND":            1,
		"APPLICATION_NOT_FOUND":       2,
		"SERVICE_NOT_FOUND":           3,
		"USER_NOT_FOUND":              4,
		"IDENTITY_NOT_FOUND":          5,
		"CREDENTIAL_NOT_FOUND":        6,
		"RELATIONSHIP_NOT_FOUND":      7,
		"GROUP_NOT_FOUND":             8,
		"KEY_NOT_FOUND":               9,
		"CHALLENGE_SETTING_NOT_FOUND": 10,
		"APPLICATION_ALREADY_EXISTS":  100,
		"CREDENTIAL_ALREADY_EXISTS":   101,
		"IDENTITY_ALREADY_EXISTS":     102,
		"TOTP_ALREADY_BOUND":          103,
		"PASSWORD_INCORRECT":          200,
		"OTP_INVALID":                 201,
		"IDP_NOT_ALLOWED":             202,
		"USER_DISABLED":               203,
		"SIGN_COUNT_ANOMALY":          204,
		"TOTP_NOT_BOUND":              205,
		"CREDENTIAL_NOT_ENABLED":      206,
		"APP_SERVICE_ACCESS_DENIED":   300,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_v1_common_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{0}
}

// Pagination 游标分页参数
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// StringList 通用字符串列表
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// BoolValue 通用布尔响应
type BoolValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolValue) Reset() {
	*x = BoolValue{}
	mi := &file_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolValue) ProtoMessage() {}

func (x *BoolValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolValue.ProtoReflect.Descriptor instead.
func (*BoolValue) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *BoolValue) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

// OpenIDRequest 以 openid 为参数的通用请求
type OpenIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenIDRequest) Reset() {
	*x = OpenIDRequest{}
	mi := &file_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIDRequest) ProtoMessage() {}

func (x *OpenIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIDRequest.ProtoReflect.Descriptor instead.
func (*OpenIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *OpenIDRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

var File_v1_common_proto protoreflect.FileDescriptor

const file_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/common.proto\x12\thermes.v1\":\n" +
	"\n" +
	"Pagination\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"!\n" +
	"\tBoolValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"'\n" +
	"\rOpenIDRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid*\xd2\x04\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DOMAIN_NOT_FOUND\x10\x01\x12\x19\n" +
	"\x15APPLICATION_NOT_FOUND\x10\x02\x12\x15\n" +
	"\x11SERVICE_NOT_FOUND\x10\x03\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x04\x12\x16\n" +
	"\x12IDENTITY_NOT_FOUND\x10\x05\x12\x18\n" +
	"\x14CREDENTIAL_NOT_FOUND\x10\x06\x12\x1a\n" +
	"\x16RELATIONSHIP_NOT_FOUND\x10\a\x12\x13\n" +
	"\x0fGROUP_NOT_FOUND\x10\b\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\t\x12\x1f\n" +
	"\x1bCHALLENGE_SETTING_NOT_FOUND\x10\n" +
	"\x12\x1e\n" +
	"\x1aAPPLICATION_ALREADY_EXISTS\x10d\x12\x1d\n" +
	"\x19CREDENTIAL_ALREADY_EXISTS\x10e\x12\x1b\n" +
	"\x17IDENTITY_ALREADY_EXISTS\x10f\x12\x16\n" +
	"\x12TOTP_ALREADY_BOUND\x10g\x12\x17\n" +
	"\x12PASSWORD_INCORRECT\x10\xc8\x01\x12\x10\n" +
	"\vOTP_INVALID\x10\xc9\x01\x12\x14\n" +
	"\x0fIDP_NOT_ALLOWED\x10\xca\x01\x12\x12\n" +
	"\rUSER_DISABLED\x10\xcb\x01\x12\x17\n" +
	"\x12SIGN_COUNT_ANOMALY\x10\xcc\x01\x12\x13\n" +
	"\x0eTOTP_NOT_BOUND\x10\xcd\x01\x12\x1b\n" +
	"\x16CREDENTIAL_NOT_ENABLED\x10\xce\x01\x12\x1e\n" +
	"\x19APP_SERVICE_ACCESS_DENIED\x10\xac\x02B\x9f\x01\n" +
	"\rcom.hermes.v1B\vCommonProtoP\x01Z<github.com/heliantheon/aegis/internal/rpc/hermes/v1;hermesv1\xa2\x02\x03HXX\xaa\x02\tHermes.V1\xca\x02\tHermes\\V1\xe2\x02\x15Hermes\\V1\\GPBMetadata\xea\x02\n" +
	"Hermes::V1b\x06proto3"

var (
	file_v1_common_proto_rawDescOnce sync.Once
	file_v1_common_proto_rawDescData []byte
)

func file_v1_common_proto_rawDescGZIP() []byte {
	file_v1_common_proto_rawDescOnce.Do(func() {
		file_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_proto_rawDesc), len(file_v1_common_proto_rawDesc)))
	})
	return file_v1_common_proto_rawDescData
}

var file_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_common_proto_goTypes = []any{
	(ErrorReason)(0),      // 0: hermes.v1.ErrorReason
	(*Pagination)(nil),    // 1: hermes.v1.Pagination
	(*StringList)(nil),    // 2: hermes.v1.StringList
	(*BoolValue)(nil),     // 3: hermes.v1.BoolValue
	(*OpenIDRequest)(nil), // 4: hermes.v1.OpenIDRequest
}
var file_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_common_proto_init() }
func file_v1_common_proto_init() {
	if File_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_proto_rawDesc), len(file_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_proto_goTypes,
		DependencyIndexes: file_v1_common_proto_depIdxs,
		EnumInfos:         file_v1_common_proto_enumTypes,
		MessageInfos:      file_v1_common_proto_msgTypes,
	}.Build()
	File_v1_common_proto = out.File
	file_v1_common_proto_goTypes = nil
	file_v1_common_proto_depIdxs = nil
}
