// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/user.proto

package hermesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Openid        string                 `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Nickname      *string                `protobuf:"bytes,4,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Picture       *string                `protobuf:"bytes,5,opt,name=picture,proto3,oneof" json:"picture,omitempty"`
	Email         *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,7,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_login_at,json=lastLoginAt,proto3,oneof" json:"last_login_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PasswordHash  *string                `protobuf:"bytes,11,opt,name=password_hash,json=passwordHash,proto3,oneof" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetPicture() string {
	if x != nil && x.Picture != nil {
		return *x.Picture
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetPasswordHash() string {
	if x != nil && x.PasswordHash != nil {
		return *x.PasswordHash
	}
	return ""
}

// DecryptedUser 解密后的用户（含明文手机号）
type DecryptedUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptedUser) Reset() {
	*x = DecryptedUser{}
	mi := &file_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptedUser) ProtoMessage() {}

func (x *DecryptedUser) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptedUser.ProtoReflect.Descriptor instead.
func (*DecryptedUser) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptedUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DecryptedUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetByIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Idp           string                 `protobuf:"bytes,2,opt,name=idp,proto3" json:"idp,omitempty"`
	TOpenid       string                 `protobuf:"bytes,3,opt,name=t_openid,json=tOpenid,proto3" json:"t_openid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdentityRequest) Reset() {
	*x = GetByIdentityRequest{}
	mi := &file_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdentityRequest) ProtoMessage() {}

func (x *GetByIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetByIdentityRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIdentityRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetByIdentityRequest) GetIdp() string {
	if x != nil {
		return x.Idp
	}
	return ""
}

func (x *GetByIdentityRequest) GetTOpenid() string {
	if x != nil {
		return x.TOpenid
	}
	return ""
}

type GetByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEmailRequest) Reset() {
	*x = GetByEmailRequest{}
	mi := &file_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEmailRequest) ProtoMessage() {}

func (x *GetByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetByPhonePlainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByPhonePlainRequest) Reset() {
	*x = GetByPhonePlainRequest{}
	mi := &file_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByPhonePlainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByPhonePlainRequest) ProtoMessage() {}

func (x *GetByPhonePlainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByPhonePlainRequest.ProtoReflect.Descriptor instead.
func (*GetByPhonePlainRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetByPhonePlainRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *UserIdentity          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	UserInfo      *TUserInfo             `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetIdentity() *UserIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *CreateUserRequest) GetUserInfo() *TUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type TUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TOpenid       string                 `protobuf:"bytes,1,opt,name=t_openid,json=tOpenid,proto3" json:"t_openid,omitempty"`
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Picture       *string                `protobuf:"bytes,5,opt,name=picture,proto3,oneof" json:"picture,omitempty"`
	RawData       *string                `protobuf:"bytes,6,opt,name=raw_data,json=rawData,proto3,oneof" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TUserInfo) Reset() {
	*x = TUserInfo{}
	mi := &file_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TUserInfo) ProtoMessage() {}

func (x *TUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TUserInfo.ProtoReflect.Descriptor instead.
func (*TUserInfo) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *TUserInfo) GetTOpenid() string {
	if x != nil {
		return x.TOpenid
	}
	return ""
}

func (x *TUserInfo) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *TUserInfo) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *TUserInfo) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *TUserInfo) GetPicture() string {
	if x != nil && x.Picture != nil {
		return *x.Picture
	}
	return ""
}

func (x *TUserInfo) GetRawData() string {
	if x != nil && x.RawData != nil {
		return *x.RawData
	}
	return ""
}

type PatchUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Picture       *string                `protobuf:"bytes,3,opt,name=picture,proto3,oneof" json:"picture,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Status        *int32                 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	PasswordHash  *string                `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3,oneof" json:"password_hash,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login_at,json=lastLoginAt,proto3,oneof" json:"last_login_at,omitempty"`
	Phone         *string                `protobuf:"bytes,8,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchUserRequest) Reset() {
	*x = PatchUserRequest{}
	mi := &file_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserRequest) ProtoMessage() {}

func (x *PatchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserRequest.ProtoReflect.Descriptor instead.
func (*PatchUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *PatchUserRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *PatchUserRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *PatchUserRequest) GetPicture() string {
	if x != nil && x.Picture != nil {
		return *x.Picture
	}
	return ""
}

func (x *PatchUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *PatchUserRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *PatchUserRequest) GetPasswordHash() string {
	if x != nil && x.PasswordHash != nil {
		return *x.PasswordHash
	}
	return ""
}

func (x *PatchUserRequest) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *PatchUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Openid        string                 `protobuf:"bytes,3,opt,name=openid,proto3" json:"openid,omitempty"` // 用户的 openid（对应 Go 模型中的 uid 字段）
	Idp           string                 `protobuf:"bytes,4,opt,name=idp,proto3" json:"idp,omitempty"`
	TOpenid       string                 `protobuf:"bytes,5,opt,name=t_openid,json=tOpenid,proto3" json:"t_openid,omitempty"`
	RawData       *string                `protobuf:"bytes,6,opt,name=raw_data,json=rawData,proto3,oneof" json:"raw_data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserIdentity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserIdentity) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UserIdentity) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *UserIdentity) GetIdp() string {
	if x != nil {
		return x.Idp
	}
	return ""
}

func (x *UserIdentity) GetTOpenid() string {
	if x != nil {
		return x.TOpenid
	}
	return ""
}

func (x *UserIdentity) GetRawData() string {
	if x != nil && x.RawData != nil {
		return *x.RawData
	}
	return ""
}

func (x *UserIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserIdentity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type IdentityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*UserIdentity        `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityList) Reset() {
	*x = IdentityList{}
	mi := &file_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityList) ProtoMessage() {}

func (x *IdentityList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityList.ProtoReflect.Descriptor instead.
func (*IdentityList) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *IdentityList) GetIdentities() []*UserIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type GetIdentityByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Openid        string                 `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	IdpType       string                 `protobuf:"bytes,3,opt,name=idp_type,json=idpType,proto3" json:"idp_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityByTypeRequest) Reset() {
	*x = GetIdentityByTypeRequest{}
	mi := &file_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityByTypeRequest) ProtoMessage() {}

func (x *GetIdentityByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityByTypeRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetIdentityByTypeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetIdentityByTypeRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetIdentityByTypeRequest) GetIdpType() string {
	if x != nil {
		return x.IdpType
	}
	return ""
}

type AddIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Openid        string                 `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Idp           string                 `protobuf:"bytes,3,opt,name=idp,proto3" json:"idp,omitempty"`
	TOpenid       string                 `protobuf:"bytes,4,opt,name=t_openid,json=tOpenid,proto3" json:"t_openid,omitempty"`
	RawData       *string                `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3,oneof" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIdentityRequest) Reset() {
	*x = AddIdentityRequest{}
	mi := &file_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIdentityRequest) ProtoMessage() {}

func (x *AddIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIdentityRequest.ProtoReflect.Descriptor instead.
func (*AddIdentityRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddIdentityRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AddIdentityRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *AddIdentityRequest) GetIdp() string {
	if x != nil {
		return x.Idp
	}
	return ""
}

func (x *AddIdentityRequest) GetTOpenid() string {
	if x != nil {
		return x.TOpenid
	}
	return ""
}

func (x *AddIdentityRequest) GetRawData() string {
	if x != nil && x.RawData != nil {
		return *x.RawData
	}
	return ""
}

type GetPasswordCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idp           string                 `protobuf:"bytes,1,opt,name=idp,proto3" json:"idp,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasswordCredentialRequest) Reset() {
	*x = GetPasswordCredentialRequest{}
	mi := &file_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasswordCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasswordCredentialRequest) ProtoMessage() {}

func (x *GetPasswordCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasswordCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetPasswordCredentialRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetPasswordCredentialRequest) GetIdp() string {
	if x != nil {
		return x.Idp
	}
	return ""
}

func (x *GetPasswordCredentialRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type PasswordStoreCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Nickname      *string                `protobuf:"bytes,3,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Picture       *string                `protobuf:"bytes,5,opt,name=picture,proto3,oneof" json:"picture,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordStoreCredential) Reset() {
	*x = PasswordStoreCredential{}
	mi := &file_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordStoreCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordStoreCredential) ProtoMessage() {}

func (x *PasswordStoreCredential) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordStoreCredential.ProtoReflect.Descriptor instead.
func (*PasswordStoreCredential) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *PasswordStoreCredential) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *PasswordStoreCredential) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *PasswordStoreCredential) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *PasswordStoreCredential) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *PasswordStoreCredential) GetPicture() string {
	if x != nil && x.Picture != nil {
		return *x.Picture
	}
	return ""
}

func (x *PasswordStoreCredential) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CredentialIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialIDRequest) Reset() {
	*x = CredentialIDRequest{}
	mi := &file_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialIDRequest) ProtoMessage() {}

func (x *CredentialIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialIDRequest.ProtoReflect.Descriptor instead.
func (*CredentialIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *CredentialIDRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type UserCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Openid        string                 `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	CredentialId  *string                `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3,oneof" json:"credential_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Secret        string                 `protobuf:"bytes,9,opt,name=secret,proto3" json:"secret,omitempty"` // 加密后的密文（gRPC 内部传输，不暴露给前端）
	Label         string                 `protobuf:"bytes,10,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredential) Reset() {
	*x = UserCredential{}
	mi := &file_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredential) ProtoMessage() {}

func (x *UserCredential) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredential.ProtoReflect.Descriptor instead.
func (*UserCredential) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserCredential) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCredential) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *UserCredential) GetCredentialId() string {
	if x != nil && x.CredentialId != nil {
		return *x.CredentialId
	}
	return ""
}

func (x *UserCredential) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserCredential) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserCredential) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *UserCredential) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserCredential) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserCredential) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UserCredential) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type UserCredentialList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*UserCredential      `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredentialList) Reset() {
	*x = UserCredentialList{}
	mi := &file_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredentialList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentialList) ProtoMessage() {}

func (x *UserCredentialList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentialList.ProtoReflect.Descriptor instead.
func (*UserCredentialList) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserCredentialList) GetCredentials() []*UserCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type CreateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	CredentialId  *string                `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3,oneof" json:"credential_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialRequest) Reset() {
	*x = CreateCredentialRequest{}
	mi := &file_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialRequest) ProtoMessage() {}

func (x *CreateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCredentialRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *CreateCredentialRequest) GetCredentialId() string {
	if x != nil && x.CredentialId != nil {
		return *x.CredentialId
	}
	return ""
}

func (x *CreateCredentialRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCredentialRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateCredentialRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetCredentialsByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsByTypeRequest) Reset() {
	*x = GetCredentialsByTypeRequest{}
	mi := &file_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsByTypeRequest) ProtoMessage() {}

func (x *GetCredentialsByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialsByTypeRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetCredentialsByTypeRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetCredentialsByTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PatchCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Secret        *string                `protobuf:"bytes,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	Label         *string                `protobuf:"bytes,4,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Enabled       *bool                  `protobuf:"varint,5,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	SignCount     *uint32                `protobuf:"varint,6,opt,name=sign_count,json=signCount,proto3,oneof" json:"sign_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCredentialRequest) Reset() {
	*x = PatchCredentialRequest{}
	mi := &file_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCredentialRequest) ProtoMessage() {}

func (x *PatchCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCredentialRequest.ProtoReflect.Descriptor instead.
func (*PatchCredentialRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *PatchCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *PatchCredentialRequest) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

func (x *PatchCredentialRequest) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *PatchCredentialRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *PatchCredentialRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *PatchCredentialRequest) GetSignCount() uint32 {
	if x != nil && x.SignCount != nil {
		return *x.SignCount
	}
	return 0
}

type DeleteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	CredentialId  string                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCredentialRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *DeleteCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type OpenIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenIDResponse) Reset() {
	*x = OpenIDResponse{}
	mi := &file_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIDResponse) ProtoMessage() {}

func (x *OpenIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIDResponse.ProtoReflect.Descriptor instead.
func (*OpenIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *OpenIDResponse) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *Group) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Group) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupList) Reset() {
	*x = GroupList{}
	mi := &file_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupList) ProtoMessage() {}

func (x *GroupList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupList.ProtoReflect.Descriptor instead.
func (*GroupList) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *GroupList) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GroupList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *CreateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{27}
}

func (x *ListGroupsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListGroupsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SetGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupMembersRequest) Reset() {
	*x = SetGroupMembersRequest{}
	mi := &file_v1_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupMembersRequest) ProtoMessage() {}

func (x *SetGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*SetGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{28}
}

func (x *SetGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_v1_user_proto protoreflect.FileDescriptor

const file_v1_user_proto_rawDesc = "" +
	"\n" +
	"\rv1/user.proto\x12\thermes.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fv1/common.proto\"\xf4\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06openid\x18\x02 \x01(\tR\x06openid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1f\n" +
	"\bnickname\x18\x04 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x1d\n" +
	"\apicture\x18\x05 \x01(\tH\x01R\apicture\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x02R\x05email\x88\x01\x01\x12%\n" +
	"\x0eemail_verified\x18\a \x01(\bR\remailVerified\x12C\n" +
	"\rlast_login_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vlastLoginAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\rpassword_hash\x18\v \x01(\tH\x04R\fpasswordHash\x88\x01\x01B\v\n" +
	"\t_nicknameB\n" +
	"\n" +
	"\b_pictureB\b\n" +
	"\x06_emailB\x10\n" +
	"\x0e_last_login_atB\x10\n" +
	"\x0e_password_hash\"J\n" +
	"\rDecryptedUser\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.hermes.v1.UserR\x04user\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"[\n" +
	"\x14GetByIdentityRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03idp\x18\x02 \x01(\tR\x03idp\x12\x19\n" +
	"\bt_openid\x18\x03 \x01(\tR\atOpenid\")\n" +
	"\x11GetByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\".\n" +
	"\x16GetByPhonePlainRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"\x8e\x01\n" +
	"\x11CreateUserRequest\x123\n" +
	"\bidentity\x18\x01 \x01(\v2\x17.hermes.v1.UserIdentityR\bidentity\x126\n" +
	"\tuser_info\x18\x02 \x01(\v2\x14.hermes.v1.TUserInfoH\x00R\buserInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_user_info\"\xf6\x01\n" +
	"\tTUserInfo\x12\x19\n" +
	"\bt_openid\x18\x01 \x01(\tR\atOpenid\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x02R\x05phone\x88\x01\x01\x12\x1d\n" +
	"\apicture\x18\x05 \x01(\tH\x03R\apicture\x88\x01\x01\x12\x1e\n" +
	"\braw_data\x18\x06 \x01(\tH\x04R\arawData\x88\x01\x01B\v\n" +
	"\t_nicknameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_pictureB\v\n" +
	"\t_raw_data\"\x88\x03\n" +
	"\x10PatchUserRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x1d\n" +
	"\apicture\x18\x03 \x01(\tH\x01R\apicture\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\x05H\x03R\x06status\x88\x01\x01\x12(\n" +
	"\rpassword_hash\x18\x06 \x01(\tH\x04R\fpasswordHash\x88\x01\x01\x12C\n" +
	"\rlast_login_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\vlastLoginAt\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\b \x01(\tH\x06R\x05phone\x88\x01\x01B\v\n" +
	"\t_nicknameB\n" +
	"\n" +
	"\b_pictureB\b\n" +
	"\x06_emailB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_password_hashB\x10\n" +
	"\x0e_last_login_atB\b\n" +
	"\x06_phone\"\x9e\x02\n" +
	"\fUserIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06openid\x18\x03 \x01(\tR\x06openid\x12\x10\n" +
	"\x03idp\x18\x04 \x01(\tR\x03idp\x12\x19\n" +
	"\bt_openid\x18\x05 \x01(\tR\atOpenid\x12\x1e\n" +
	"\braw_data\x18\x06 \x01(\tH\x00R\arawData\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_raw_data\"G\n" +
	"\fIdentityList\x127\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x17.hermes.v1.UserIdentityR\n" +
	"identities\"e\n" +
	"\x18GetIdentityByTypeRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06openid\x18\x02 \x01(\tR\x06openid\x12\x19\n" +
	"\bidp_type\x18\x03 \x01(\tR\aidpType\"\x9e\x01\n" +
	"\x12AddIdentityRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06openid\x18\x02 \x01(\tR\x06openid\x12\x10\n" +
	"\x03idp\x18\x03 \x01(\tR\x03idp\x12\x19\n" +
	"\bt_openid\x18\x04 \x01(\tR\atOpenid\x12\x1e\n" +
	"\braw_data\x18\x05 \x01(\tH\x00R\arawData\x88\x01\x01B\v\n" +
	"\t_raw_data\"P\n" +
	"\x1cGetPasswordCredentialRequest\x12\x10\n" +
	"\x03idp\x18\x01 \x01(\tR\x03idp\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"\xec\x01\n" +
	"\x17PasswordStoreCredential\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x1f\n" +
	"\bnickname\x18\x03 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x1d\n" +
	"\apicture\x18\x05 \x01(\tH\x02R\apicture\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06statusB\v\n" +
	"\t_nicknameB\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_picture\":\n" +
	"\x13CredentialIDRequest\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\"\x9a\x03\n" +
	"\x0eUserCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06openid\x18\x02 \x01(\tR\x06openid\x12(\n" +
	"\rcredential_id\x18\x03 \x01(\tH\x00R\fcredentialId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12A\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastUsedAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06secret\x18\t \x01(\tR\x06secret\x12\x14\n" +
	"\x05label\x18\n" +
	" \x01(\tR\x05labelB\x10\n" +
	"\x0e_credential_idB\x0f\n" +
	"\r_last_used_at\"Q\n" +
	"\x12UserCredentialList\x12;\n" +
	"\vcredentials\x18\x01 \x03(\v2\x19.hermes.v1.UserCredentialR\vcredentials\"\xaf\x01\n" +
	"\x17CreateCredentialRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12(\n" +
	"\rcredential_id\x18\x02 \x01(\tH\x00R\fcredentialId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05labelB\x10\n" +
	"\x0e_credential_id\"I\n" +
	"\x1bGetCredentialsByTypeRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xbc\x02\n" +
	"\x16PatchCredentialRequest\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x1b\n" +
	"\x06secret\x18\x02 \x01(\tH\x00R\x06secret\x88\x01\x01\x12A\n" +
	"\flast_used_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastUsedAt\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\x04 \x01(\tH\x02R\x05label\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x05 \x01(\bH\x03R\aenabled\x88\x01\x01\x12\"\n" +
	"\n" +
	"sign_count\x18\x06 \x01(\rH\x04R\tsignCount\x88\x01\x01B\t\n" +
	"\a_secretB\x0f\n" +
	"\r_last_used_atB\b\n" +
	"\x06_labelB\n" +
	"\n" +
	"\b_enabledB\r\n" +
	"\v_sign_count\"V\n" +
	"\x17DeleteCredentialRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\"(\n" +
	"\x0eOpenIDResponse\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\"\x92\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_description\"V\n" +
	"\tGroupList\x12(\n" +
	"\x06groups\x18\x01 \x03(\v2\x10.hermes.v1.GroupR\x06groups\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x99\x01\n" +
	"\x12CreateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x88\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"b\n" +
	"\x11ListGroupsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.hermes.v1.PaginationR\n" +
	"pagination\"N\n" +
	"\x16SetGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds2\xd2\x10\n" +
	"\vUserService\x128\n" +
	"\vGetByOpenID\x12\x18.hermes.v1.OpenIDRequest\x1a\x0f.hermes.v1.User\x12A\n" +
	"\rGetByIdentity\x12\x1f.hermes.v1.GetByIdentityRequest\x1a\x0f.hermes.v1.User\x12D\n" +
	"\n" +
	"GetByEmail\x12\x1c.hermes.v1.GetByEmailRequest\x1a\x18.hermes.v1.DecryptedUser\x12N\n" +
	"\x0fGetByPhonePlain\x12!.hermes.v1.GetByPhonePlainRequest\x1a\x18.hermes.v1.DecryptedUser\x12F\n" +
	"\x10GetDecryptedUser\x12\x18.hermes.v1.OpenIDRequest\x1a\x18.hermes.v1.DecryptedUser\x12W\n" +
	"\x1aGetDecryptedUserByIdentity\x12\x1f.hermes.v1.GetByIdentityRequest\x1a\x18.hermes.v1.DecryptedUser\x12D\n" +
	"\n" +
	"CreateUser\x12\x1c.hermes.v1.CreateUserRequest\x1a\x18.hermes.v1.DecryptedUser\x129\n" +
	"\tPatchUser\x12\x1b.hermes.v1.PatchUserRequest\x1a\x0f.hermes.v1.User\x12B\n" +
	"\rGetIdentities\x12\x18.hermes.v1.OpenIDRequest\x1a\x17.hermes.v1.IdentityList\x12S\n" +
	"\x17GetIdentitiesByIdentity\x12\x1f.hermes.v1.GetByIdentityRequest\x1a\x17.hermes.v1.IdentityList\x12Q\n" +
	"\x11GetIdentityByType\x12#.hermes.v1.GetIdentityByTypeRequest\x1a\x17.hermes.v1.UserIdentity\x12D\n" +
	"\vAddIdentity\x12\x1d.hermes.v1.AddIdentityRequest\x1a\x16.google.protobuf.Empty\x12d\n" +
	"\x15GetPasswordCredential\x12'.hermes.v1.GetPasswordCredentialRequest\x1a\".hermes.v1.PasswordStoreCredential\x12N\n" +
	"\x10CreateCredential\x12\".hermes.v1.CreateCredentialRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x11GetCredentialByID\x12\x1e.hermes.v1.CredentialIDRequest\x1a\x19.hermes.v1.UserCredential\x12M\n" +
	"\x12GetUserCredentials\x12\x18.hermes.v1.OpenIDRequest\x1a\x1d.hermes.v1.UserCredentialList\x12a\n" +
	"\x18GetUserCredentialsByType\x12&.hermes.v1.GetCredentialsByTypeRequest\x1a\x1d.hermes.v1.UserCredentialList\x12L\n" +
	"\x0fPatchCredential\x12!.hermes.v1.PatchCredentialRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x10DeleteCredential\x12\".hermes.v1.DeleteCredentialRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x1bDeleteUserCredentialsByType\x12&.hermes.v1.GetCredentialsByTypeRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x17GetOpenIDByCredentialID\x12\x1e.hermes.v1.CredentialIDRequest\x1a\x19.hermes.v1.OpenIDResponse\x12>\n" +
	"\vCreateGroup\x12\x1d.hermes.v1.CreateGroupRequest\x1a\x10.hermes.v1.Group\x128\n" +
	"\bGetGroup\x12\x1a.hermes.v1.GetGroupRequest\x1a\x10.hermes.v1.Group\x12@\n" +
	"\n" +
	"ListGroups\x12\x1c.hermes.v1.ListGroupsRequest\x1a\x14.hermes.v1.GroupList\x12>\n" +
	"\vUpdateGroup\x12\x1d.hermes.v1.UpdateGroupRequest\x1a\x10.hermes.v1.Group\x12A\n" +
	"\vDeleteGroup\x12\x1a.hermes.v1.GetGroupRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fSetGroupMembers\x12!.hermes.v1.SetGroupMembersRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x0fGetGroupMembers\x12\x1a.hermes.v1.GetGroupRequest\x1a\x15.hermes.v1.StringListB\x9d\x01\n" +
	"\rcom.hermes.v1B\tUserProtoP\x01Z<github.com/heliantheon/aegis/internal/rpc/hermes/v1;hermesv1\xa2\x02\x03HXX\xaa\x02\tHermes.V1\xca\x02\tHermes\\V1\xe2\x02\x15Hermes\\V1\\GPBMetadata\xea\x02\n" +
	"Hermes::V1b\x06proto3"

var (
	file_v1_user_proto_rawDescOnce sync.Once
	file_v1_user_proto_rawDescData []byte
)

func file_v1_user_proto_rawDescGZIP() []byte {
	file_v1_user_proto_rawDescOnce.Do(func() {
		file_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)))
	})
	return file_v1_user_proto_rawDescData
}

var file_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_v1_user_proto_goTypes = []any{
	(*User)(nil),                         // 0: hermes.v1.User
	(*DecryptedUser)(nil),                // 1: hermes.v1.DecryptedUser
	(*GetByIdentityRequest)(nil),         // 2: hermes.v1.GetByIdentityRequest
	(*GetByEmailRequest)(nil),            // 3: hermes.v1.GetByEmailRequest
	(*GetByPhonePlainRequest)(nil),       // 4: hermes.v1.GetByPhonePlainRequest
	(*CreateUserRequest)(nil),            // 5: hermes.v1.CreateUserRequest
	(*TUserInfo)(nil),                    // 6: hermes.v1.TUserInfo
	(*PatchUserRequest)(nil),             // 7: hermes.v1.PatchUserRequest
	(*UserIdentity)(nil),                 // 8: hermes.v1.UserIdentity
	(*IdentityList)(nil),                 // 9: hermes.v1.IdentityList
	(*GetIdentityByTypeRequest)(nil),     // 10: hermes.v1.GetIdentityByTypeRequest
	(*AddIdentityRequest)(nil),           // 11: hermes.v1.AddIdentityRequest
	(*GetPasswordCredentialRequest)(nil), // 12: hermes.v1.GetPasswordCredentialRequest
	(*PasswordStoreCredential)(nil),      // 13: hermes.v1.PasswordStoreCredential
	(*CredentialIDRequest)(nil),          // 14: hermes.v1.CredentialIDRequest
	(*UserCredential)(nil),               // 15: hermes.v1.UserCredential
	(*UserCredentialList)(nil),           // 16: hermes.v1.UserCredentialList
	(*CreateCredentialRequest)(nil),      // 17: hermes.v1.CreateCredentialRequest
	(*GetCredentialsByTypeRequest)(nil),  // 18: hermes.v1.GetCredentialsByTypeRequest
	(*PatchCredentialRequest)(nil),       // 19: hermes.v1.PatchCredentialRequest
	(*DeleteCredentialRequest)(nil),      // 20: hermes.v1.DeleteCredentialRequest
	(*OpenIDResponse)(nil),               // 21: hermes.v1.OpenIDResponse
	(*Group)(nil),                        // 22: hermes.v1.Group
	(*GroupList)(nil),                    // 23: hermes.v1.GroupList
	(*GetGroupRequest)(nil),              // 24: hermes.v1.GetGroupRequest
	(*CreateGroupRequest)(nil),           // 25: hermes.v1.CreateGroupRequest
	(*UpdateGroupRequest)(nil),           // 26: hermes.v1.UpdateGroupRequest
	(*ListGroupsRequest)(nil),            // 27: hermes.v1.ListGroupsRequest
	(*SetGroupMembersRequest)(nil),       // 28: hermes.v1.SetGroupMembersRequest
	(*timestamppb.Timestamp)(nil),        // 29: google.protobuf.Timestamp
	(*Pagination)(nil),                   // 30: hermes.v1.Pagination
	(*OpenIDRequest)(nil),                // 31: hermes.v1.OpenIDRequest
	(*emptypb.Empty)(nil),                // 32: google.protobuf.Empty
	(*StringList)(nil),                   // 33: hermes.v1.StringList
}
var file_v1_user_proto_depIdxs = []int32{
	29, // 0: hermes.v1.User.last_login_at:type_name -> google.protobuf.Timestamp
	29, // 1: hermes.v1.User.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: hermes.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: hermes.v1.DecryptedUser.user:type_name -> hermes.v1.User
	8,  // 4: hermes.v1.CreateUserRequest.identity:type_name -> hermes.v1.UserIdentity
	6,  // 5: hermes.v1.CreateUserRequest.user_info:type_name -> hermes.v1.TUserInfo
	29, // 6: hermes.v1.PatchUserRequest.last_login_at:type_name -> google.protobuf.Timestamp
	29, // 7: hermes.v1.UserIdentity.created_at:type_name -> google.protobuf.Timestamp
	29, // 8: hermes.v1.UserIdentity.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 9: hermes.v1.IdentityList.identities:type_name -> hermes.v1.UserIdentity
	29, // 10: hermes.v1.UserCredential.last_used_at:type_name -> google.protobuf.Timestamp
	29, // 11: hermes.v1.UserCredential.created_at:type_name -> google.protobuf.Timestamp
	29, // 12: hermes.v1.UserCredential.updated_at:type_name -> google.protobuf.Timestamp
	15, // 13: hermes.v1.UserCredentialList.credentials:type_name -> hermes.v1.UserCredential
	29, // 14: hermes.v1.PatchCredentialRequest.last_used_at:type_name -> google.protobuf.Timestamp
	29, // 15: hermes.v1.Group.created_at:type_name -> google.protobuf.Timestamp
	29, // 16: hermes.v1.Group.updated_at:type_name -> google.protobuf.Timestamp
	22, // 17: hermes.v1.GroupList.groups:type_name -> hermes.v1.Group
	30, // 18: hermes.v1.ListGroupsRequest.pagination:type_name -> hermes.v1.Pagination
	31, // 19: hermes.v1.UserService.GetByOpenID:input_type -> hermes.v1.OpenIDRequest
	2,  // 20: hermes.v1.UserService.GetByIdentity:input_type -> hermes.v1.GetByIdentityRequest
	3,  // 21: hermes.v1.UserService.GetByEmail:input_type -> hermes.v1.GetByEmailRequest
	4,  // 22: hermes.v1.UserService.GetByPhonePlain:input_type -> hermes.v1.GetByPhonePlainRequest
	31, // 23: hermes.v1.UserService.GetDecryptedUser:input_type -> hermes.v1.OpenIDRequest
	2,  // 24: hermes.v1.UserService.GetDecryptedUserByIdentity:input_type -> hermes.v1.GetByIdentityRequest
	5,  // 25: hermes.v1.UserService.CreateUser:input_type -> hermes.v1.CreateUserRequest
	7,  // 26: hermes.v1.UserService.PatchUser:input_type -> hermes.v1.PatchUserRequest
	31, // 27: hermes.v1.UserService.GetIdentities:input_type -> hermes.v1.OpenIDRequest
	2,  // 28: hermes.v1.UserService.GetIdentitiesByIdentity:input_type -> hermes.v1.GetByIdentityRequest
	10, // 29: hermes.v1.UserService.GetIdentityByType:input_type -> hermes.v1.GetIdentityByTypeRequest
	11, // 30: hermes.v1.UserService.AddIdentity:input_type -> hermes.v1.AddIdentityRequest
	12, // 31: hermes.v1.UserService.GetPasswordCredential:input_type -> hermes.v1.GetPasswordCredentialRequest
	17, // 32: hermes.v1.UserService.CreateCredential:input_type -> hermes.v1.CreateCredentialRequest
	14, // 33: hermes.v1.UserService.GetCredentialByID:input_type -> hermes.v1.CredentialIDRequest
	31, // 34: hermes.v1.UserService.GetUserCredentials:input_type -> hermes.v1.OpenIDRequest
	18, // 35: hermes.v1.UserService.GetUserCredentialsByType:input_type -> hermes.v1.GetCredentialsByTypeRequest
	19, // 36: hermes.v1.UserService.PatchCredential:input_type -> hermes.v1.PatchCredentialRequest
	20, // 37: hermes.v1.UserService.DeleteCredential:input_type -> hermes.v1.DeleteCredentialRequest
	18, // 38: hermes.v1.UserService.DeleteUserCredentialsByType:input_type -> hermes.v1.GetCredentialsByTypeRequest
	14, // 39: hermes.v1.UserService.GetOpenIDByCredentialID:input_type -> hermes.v1.CredentialIDRequest
	25, // 40: hermes.v1.UserService.CreateGroup:input_type -> hermes.v1.CreateGroupRequest
	24, // 41: hermes.v1.UserService.GetGroup:input_type -> hermes.v1.GetGroupRequest
	27, // 42: hermes.v1.UserService.ListGroups:input_type -> hermes.v1.ListGroupsRequest
	26, // 43: hermes.v1.UserService.UpdateGroup:input_type -> hermes.v1.UpdateGroupRequest
	24, // 44: hermes.v1.UserService.DeleteGroup:input_type -> hermes.v1.GetGroupRequest
	28, // 45: hermes.v1.UserService.SetGroupMembers:input_type -> hermes.v1.SetGroupMembersRequest
	24, // 46: hermes.v1.UserService.GetGroupMembers:input_type -> hermes.v1.GetGroupRequest
	0,  // 47: hermes.v1.UserService.GetByOpenID:output_type -> hermes.v1.User
	0,  // 48: hermes.v1.UserService.GetByIdentity:output_type -> hermes.v1.User
	1,  // 49: hermes.v1.UserService.GetByEmail:output_type -> hermes.v1.DecryptedUser
	1,  // 50: hermes.v1.UserService.GetByPhonePlain:output_type -> hermes.v1.DecryptedUser
	1,  // 51: hermes.v1.UserService.GetDecryptedUser:output_type -> hermes.v1.DecryptedUser
	1,  // 52: hermes.v1.UserService.GetDecryptedUserByIdentity:output_type -> hermes.v1.DecryptedUser
	1,  // 53: hermes.v1.UserService.CreateUser:output_type -> hermes.v1.DecryptedUser
	0,  // 54: hermes.v1.UserService.PatchUser:output_type -> hermes.v1.User
	9,  // 55: hermes.v1.UserService.GetIdentities:output_type -> hermes.v1.IdentityList
	9,  // 56: hermes.v1.UserService.GetIdentitiesByIdentity:output_type -> hermes.v1.IdentityList
	8,  // 57: hermes.v1.UserService.GetIdentityByType:output_type -> hermes.v1.UserIdentity
	32, // 58: hermes.v1.UserService.AddIdentity:output_type -> google.protobuf.Empty
	13, // 59: hermes.v1.UserService.GetPasswordCredential:output_type -> hermes.v1.PasswordStoreCredential
	32, // 60: hermes.v1.UserService.CreateCredential:output_type -> google.protobuf.Empty
	15, // 61: hermes.v1.UserService.GetCredentialByID:output_type -> hermes.v1.UserCredential
	16, // 62: hermes.v1.UserService.GetUserCredentials:output_type -> hermes.v1.UserCredentialList
	16, // 63: hermes.v1.UserService.GetUserCredentialsByType:output_type -> hermes.v1.UserCredentialList
	32, // 64: hermes.v1.UserService.PatchCredential:output_type -> google.protobuf.Empty
	32, // 65: hermes.v1.UserService.DeleteCredential:output_type -> google.protobuf.Empty
	32, // 66: hermes.v1.UserService.DeleteUserCredentialsByType:output_type -> google.protobuf.Empty
	21, // 67: hermes.v1.UserService.GetOpenIDByCredentialID:output_type -> hermes.v1.OpenIDResponse
	22, // 68: hermes.v1.UserService.CreateGroup:output_type -> hermes.v1.Group
	22, // 69: hermes.v1.UserService.GetGroup:output_type -> hermes.v1.Group
	23, // 70: hermes.v1.UserService.ListGroups:output_type -> hermes.v1.GroupList
	22, // 71: hermes.v1.UserService.UpdateGroup:output_type -> hermes.v1.Group
	32, // 72: hermes.v1.UserService.DeleteGroup:output_type -> google.protobuf.Empty
	32, // 73: hermes.v1.UserService.SetGroupMembers:output_type -> google.protobuf.Empty
	33, // 74: hermes.v1.UserService.GetGroupMembers:output_type -> hermes.v1.StringList
	47, // [47:75] is the sub-list for method output_type
	19, // [19:47] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_v1_user_proto_init() }
func file_v1_user_proto_init() {
	if File_v1_user_proto != nil {
		return
	}
	file_v1_common_proto_init()
	file_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[5].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[6].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[7].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[8].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[11].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[13].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[15].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[17].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[19].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[22].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[25].OneofWrappers = []any{}
	file_v1_user_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_proto_goTypes,
		DependencyIndexes: file_v1_user_proto_depIdxs,
		MessageInfos:      file_v1_user_proto_msgTypes,
	}.Build()
	File_v1_user_proto = out.File
	file_v1_user_proto_goTypes = nil
	file_v1_user_proto_depIdxs = nil
}
