// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/user.proto

package hermesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetByOpenID_FullMethodName                 = "/hermes.v1.UserService/GetByOpenID"
	UserService_GetByIdentity_FullMethodName               = "/hermes.v1.UserService/GetByIdentity"
	UserService_GetByEmail_FullMethodName                  = "/hermes.v1.UserService/GetByEmail"
	UserService_GetByPhonePlain_FullMethodName             = "/hermes.v1.UserService/GetByPhonePlain"
	UserService_GetDecryptedUser_FullMethodName            = "/hermes.v1.UserService/GetDecryptedUser"
	UserService_GetDecryptedUserByIdentity_FullMethodName  = "/hermes.v1.UserService/GetDecryptedUserByIdentity"
	UserService_CreateUser_FullMethodName                  = "/hermes.v1.UserService/CreateUser"
	UserService_PatchUser_FullMethodName                   = "/hermes.v1.UserService/PatchUser"
	UserService_GetIdentities_FullMethodName               = "/hermes.v1.UserService/GetIdentities"
	UserService_GetIdentitiesByIdentity_FullMethodName     = "/hermes.v1.UserService/GetIdentitiesByIdentity"
	UserService_GetIdentityByType_FullMethodName           = "/hermes.v1.UserService/GetIdentityByType"
	UserService_AddIdentity_FullMethodName                 = "/hermes.v1.UserService/AddIdentity"
	UserService_GetPasswordCredential_FullMethodName       = "/hermes.v1.UserService/GetPasswordCredential"
	UserService_CreateCredential_FullMethodName            = "/hermes.v1.UserService/CreateCredential"
	UserService_GetCredentialByID_FullMethodName           = "/hermes.v1.UserService/GetCredentialByID"
	UserService_GetUserCredentials_FullMethodName          = "/hermes.v1.UserService/GetUserCredentials"
	UserService_GetUserCredentialsByType_FullMethodName    = "/hermes.v1.UserService/GetUserCredentialsByType"
	UserService_PatchCredential_FullMethodName             = "/hermes.v1.UserService/PatchCredential"
	UserService_DeleteCredential_FullMethodName            = "/hermes.v1.UserService/DeleteCredential"
	UserService_DeleteUserCredentialsByType_FullMethodName = "/hermes.v1.UserService/DeleteUserCredentialsByType"
	UserService_GetOpenIDByCredentialID_FullMethodName     = "/hermes.v1.UserService/GetOpenIDByCredentialID"
	UserService_CreateGroup_FullMethodName                 = "/hermes.v1.UserService/CreateGroup"
	UserService_GetGroup_FullMethodName                    = "/hermes.v1.UserService/GetGroup"
	UserService_ListGroups_FullMethodName                  = "/hermes.v1.UserService/ListGroups"
	UserService_UpdateGroup_FullMethodName                 = "/hermes.v1.UserService/UpdateGroup"
	UserService_DeleteGroup_FullMethodName                 = "/hermes.v1.UserService/DeleteGroup"
	UserService_SetGroupMembers_FullMethodName             = "/hermes.v1.UserService/SetGroupMembers"
	UserService_GetGroupMembers_FullMethodName             = "/hermes.v1.UserService/GetGroupMembers"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserService 用户 + 身份 + 凭证（TOTP/WebAuthn）+ MFA + 密码认证 + 用户组
type UserServiceClient interface {
	GetByOpenID(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*User, error)
	GetByIdentity(ctx context.Context, in *GetByIdentityRequest, opts ...grpc.CallOption) (*User, error)
	GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*DecryptedUser, error)
	GetByPhonePlain(ctx context.Context, in *GetByPhonePlainRequest, opts ...grpc.CallOption) (*DecryptedUser, error)
	GetDecryptedUser(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*DecryptedUser, error)
	GetDecryptedUserByIdentity(ctx context.Context, in *GetByIdentityRequest, opts ...grpc.CallOption) (*DecryptedUser, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*DecryptedUser, error)
	PatchUser(ctx context.Context, in *PatchUserRequest, opts ...grpc.CallOption) (*User, error)
	GetIdentities(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*IdentityList, error)
	GetIdentitiesByIdentity(ctx context.Context, in *GetByIdentityRequest, opts ...grpc.CallOption) (*IdentityList, error)
	GetIdentityByType(ctx context.Context, in *GetIdentityByTypeRequest, opts ...grpc.CallOption) (*UserIdentity, error)
	AddIdentity(ctx context.Context, in *AddIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPasswordCredential(ctx context.Context, in *GetPasswordCredentialRequest, opts ...grpc.CallOption) (*PasswordStoreCredential, error)
	CreateCredential(ctx context.Context, in *CreateCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCredentialByID(ctx context.Context, in *CredentialIDRequest, opts ...grpc.CallOption) (*UserCredential, error)
	GetUserCredentials(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*UserCredentialList, error)
	GetUserCredentialsByType(ctx context.Context, in *GetCredentialsByTypeRequest, opts ...grpc.CallOption) (*UserCredentialList, error)
	PatchCredential(ctx context.Context, in *PatchCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteUserCredentialsByType(ctx context.Context, in *GetCredentialsByTypeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetOpenIDByCredentialID(ctx context.Context, in *CredentialIDRequest, opts ...grpc.CallOption) (*OpenIDResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*Group, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*GroupList, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	DeleteGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetGroupMembers(ctx context.Context, in *SetGroupMembersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetGroupMembers(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*StringList, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetByOpenID(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_GetByOpenID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByIdentity(ctx context.Context, in *GetByIdentityRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_GetByIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*DecryptedUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptedUser)
	err := c.cc.Invoke(ctx, UserService_GetByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByPhonePlain(ctx context.Context, in *GetByPhonePlainRequest, opts ...grpc.CallOption) (*DecryptedUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptedUser)
	err := c.cc.Invoke(ctx, UserService_GetByPhonePlain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetDecryptedUser(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*DecryptedUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptedUser)
	err := c.cc.Invoke(ctx, UserService_GetDecryptedUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetDecryptedUserByIdentity(ctx context.Context, in *GetByIdentityRequest, opts ...grpc.CallOption) (*DecryptedUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptedUser)
	err := c.cc.Invoke(ctx, UserService_GetDecryptedUserByIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*DecryptedUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptedUser)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PatchUser(ctx context.Context, in *PatchUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_PatchUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIdentities(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*IdentityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityList)
	err := c.cc.Invoke(ctx, UserService_GetIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIdentitiesByIdentity(ctx context.Context, in *GetByIdentityRequest, opts ...grpc.CallOption) (*IdentityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityList)
	err := c.cc.Invoke(ctx, UserService_GetIdentitiesByIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIdentityByType(ctx context.Context, in *GetIdentityByTypeRequest, opts ...grpc.CallOption) (*UserIdentity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserIdentity)
	err := c.cc.Invoke(ctx, UserService_GetIdentityByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddIdentity(ctx context.Context, in *AddIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_AddIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPasswordCredential(ctx context.Context, in *GetPasswordCredentialRequest, opts ...grpc.CallOption) (*PasswordStoreCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordStoreCredential)
	err := c.cc.Invoke(ctx, UserService_GetPasswordCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateCredential(ctx context.Context, in *CreateCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_CreateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCredentialByID(ctx context.Context, in *CredentialIDRequest, opts ...grpc.CallOption) (*UserCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredential)
	err := c.cc.Invoke(ctx, UserService_GetCredentialByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserCredentials(ctx context.Context, in *OpenIDRequest, opts ...grpc.CallOption) (*UserCredentialList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredentialList)
	err := c.cc.Invoke(ctx, UserService_GetUserCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserCredentialsByType(ctx context.Context, in *GetCredentialsByTypeRequest, opts ...grpc.CallOption) (*UserCredentialList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredentialList)
	err := c.cc.Invoke(ctx, UserService_GetUserCredentialsByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PatchCredential(ctx context.Context, in *PatchCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_PatchCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserCredentialsByType(ctx context.Context, in *GetCredentialsByTypeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_DeleteUserCredentialsByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetOpenIDByCredentialID(ctx context.Context, in *CredentialIDRequest, opts ...grpc.CallOption) (*OpenIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenIDResponse)
	err := c.cc.Invoke(ctx, UserService_GetOpenIDByCredentialID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, UserService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, UserService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*GroupList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupList)
	err := c.cc.Invoke(ctx, UserService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, UserService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetGroupMembers(ctx context.Context, in *SetGroupMembersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_SetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGroupMembers(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*StringList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringList)
	err := c.cc.Invoke(ctx, UserService_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// UserService 用户 + 身份 + 凭证（TOTP/WebAuthn）+ MFA + 密码认证 + 用户组
type UserServiceServer interface {
	GetByOpenID(context.Context, *OpenIDRequest) (*User, error)
	GetByIdentity(context.Context, *GetByIdentityRequest) (*User, error)
	GetByEmail(context.Context, *GetByEmailRequest) (*DecryptedUser, error)
	GetByPhonePlain(context.Context, *GetByPhonePlainRequest) (*DecryptedUser, error)
	GetDecryptedUser(context.Context, *OpenIDRequest) (*DecryptedUser, error)
	GetDecryptedUserByIdentity(context.Context, *GetByIdentityRequest) (*DecryptedUser, error)
	CreateUser(context.Context, *CreateUserRequest) (*DecryptedUser, error)
	PatchUser(context.Context, *PatchUserRequest) (*User, error)
	GetIdentities(context.Context, *OpenIDRequest) (*IdentityList, error)
	GetIdentitiesByIdentity(context.Context, *GetByIdentityRequest) (*IdentityList, error)
	GetIdentityByType(context.Context, *GetIdentityByTypeRequest) (*UserIdentity, error)
	AddIdentity(context.Context, *AddIdentityRequest) (*emptypb.Empty, error)
	GetPasswordCredential(context.Context, *GetPasswordCredentialRequest) (*PasswordStoreCredential, error)
	CreateCredential(context.Context, *CreateCredentialRequest) (*emptypb.Empty, error)
	GetCredentialByID(context.Context, *CredentialIDRequest) (*UserCredential, error)
	GetUserCredentials(context.Context, *OpenIDRequest) (*UserCredentialList, error)
	GetUserCredentialsByType(context.Context, *GetCredentialsByTypeRequest) (*UserCredentialList, error)
	PatchCredential(context.Context, *PatchCredentialRequest) (*emptypb.Empty, error)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*emptypb.Empty, error)
	DeleteUserCredentialsByType(context.Context, *GetCredentialsByTypeRequest) (*emptypb.Empty, error)
	GetOpenIDByCredentialID(context.Context, *CredentialIDRequest) (*OpenIDResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	GetGroup(context.Context, *GetGroupRequest) (*Group, error)
	ListGroups(context.Context, *ListGroupsRequest) (*GroupList, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*Group, error)
	DeleteGroup(context.Context, *GetGroupRequest) (*emptypb.Empty, error)
	SetGroupMembers(context.Context, *SetGroupMembersRequest) (*emptypb.Empty, error)
	GetGroupMembers(context.Context, *GetGroupRequest) (*StringList, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetByOpenID(context.Context, *OpenIDRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByOpenID not implemented")
}
func (UnimplementedUserServiceServer) GetByIdentity(context.Context, *GetByIdentityRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByIdentity not implemented")
}
func (UnimplementedUserServiceServer) GetByEmail(context.Context, *GetByEmailRequest) (*DecryptedUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByEmail not implemented")
}
func (UnimplementedUserServiceServer) GetByPhonePlain(context.Context, *GetByPhonePlainRequest) (*DecryptedUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByPhonePlain not implemented")
}
func (UnimplementedUserServiceServer) GetDecryptedUser(context.Context, *OpenIDRequest) (*DecryptedUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecryptedUser not implemented")
}
func (UnimplementedUserServiceServer) GetDecryptedUserByIdentity(context.Context, *GetByIdentityRequest) (*DecryptedUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecryptedUserByIdentity not implemented")
}
func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*DecryptedUser, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) PatchUser(context.Context, *PatchUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchUser not implemented")
}
func (UnimplementedUserServiceServer) GetIdentities(context.Context, *OpenIDRequest) (*IdentityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentities not implemented")
}
func (UnimplementedUserServiceServer) GetIdentitiesByIdentity(context.Context, *GetByIdentityRequest) (*IdentityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentitiesByIdentity not implemented")
}
func (UnimplementedUserServiceServer) GetIdentityByType(context.Context, *GetIdentityByTypeRequest) (*UserIdentity, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityByType not implemented")
}
func (UnimplementedUserServiceServer) AddIdentity(context.Context, *AddIdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIdentity not implemented")
}
func (UnimplementedUserServiceServer) GetPasswordCredential(context.Context, *GetPasswordCredentialRequest) (*PasswordStoreCredential, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPasswordCredential not implemented")
}
func (UnimplementedUserServiceServer) CreateCredential(context.Context, *CreateCredentialRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCredential not implemented")
}
func (UnimplementedUserServiceServer) GetCredentialByID(context.Context, *CredentialIDRequest) (*UserCredential, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialByID not implemented")
}
func (UnimplementedUserServiceServer) GetUserCredentials(context.Context, *OpenIDRequest) (*UserCredentialList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCredentials not implemented")
}
func (UnimplementedUserServiceServer) GetUserCredentialsByType(context.Context, *GetCredentialsByTypeRequest) (*UserCredentialList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCredentialsByType not implemented")
}
func (UnimplementedUserServiceServer) PatchCredential(context.Context, *PatchCredentialRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchCredential not implemented")
}
func (UnimplementedUserServiceServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserCredentialsByType(context.Context, *GetCredentialsByTypeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserCredentialsByType not implemented")
}
func (UnimplementedUserServiceServer) GetOpenIDByCredentialID(context.Context, *CredentialIDRequest) (*OpenIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenIDByCredentialID not implemented")
}
func (UnimplementedUserServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedUserServiceServer) GetGroup(context.Context, *GetGroupRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedUserServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*GroupList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedUserServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedUserServiceServer) DeleteGroup(context.Context, *GetGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedUserServiceServer) SetGroupMembers(context.Context, *SetGroupMembersRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroupMembers not implemented")
}
func (UnimplementedUserServiceServer) GetGroupMembers(context.Context, *GetGroupRequest) (*StringList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetByOpenID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByOpenID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetByOpenID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByOpenID(ctx, req.(*OpenIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetByIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByIdentity(ctx, req.(*GetByIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByEmail(ctx, req.(*GetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByPhonePlain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByPhonePlainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByPhonePlain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetByPhonePlain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByPhonePlain(ctx, req.(*GetByPhonePlainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetDecryptedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetDecryptedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetDecryptedUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetDecryptedUser(ctx, req.(*OpenIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetDecryptedUserByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetDecryptedUserByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetDecryptedUserByIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetDecryptedUserByIdentity(ctx, req.(*GetByIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PatchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PatchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_PatchUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PatchUser(ctx, req.(*PatchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIdentities(ctx, req.(*OpenIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIdentitiesByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIdentitiesByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIdentitiesByIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIdentitiesByIdentity(ctx, req.(*GetByIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIdentityByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIdentityByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIdentityByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIdentityByType(ctx, req.(*GetIdentityByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddIdentity(ctx, req.(*AddIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPasswordCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPasswordCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPasswordCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPasswordCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPasswordCredential(ctx, req.(*GetPasswordCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateCredential(ctx, req.(*CreateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCredentialByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCredentialByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetCredentialByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCredentialByID(ctx, req.(*CredentialIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserCredentials(ctx, req.(*OpenIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserCredentialsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialsByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserCredentialsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserCredentialsByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserCredentialsByType(ctx, req.(*GetCredentialsByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PatchCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PatchCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_PatchCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PatchCredential(ctx, req.(*PatchCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserCredentialsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialsByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserCredentialsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUserCredentialsByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserCredentialsByType(ctx, req.(*GetCredentialsByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetOpenIDByCredentialID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetOpenIDByCredentialID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetOpenIDByCredentialID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetOpenIDByCredentialID(ctx, req.(*CredentialIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetGroupMembers(ctx, req.(*SetGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGroupMembers(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hermes.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByOpenID",
			Handler:    _UserService_GetByOpenID_Handler,
		},
		{
			MethodName: "GetByIdentity",
			Handler:    _UserService_GetByIdentity_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _UserService_GetByEmail_Handler,
		},
		{
			MethodName: "GetByPhonePlain",
			Handler:    _UserService_GetByPhonePlain_Handler,
		},
		{
			MethodName: "GetDecryptedUser",
			Handler:    _UserService_GetDecryptedUser_Handler,
		},
		{
			MethodName: "GetDecryptedUserByIdentity",
			Handler:    _UserService_GetDecryptedUserByIdentity_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "PatchUser",
			Handler:    _UserService_PatchUser_Handler,
		},
		{
			MethodName: "GetIdentities",
			Handler:    _UserService_GetIdentities_Handler,
		},
		{
			MethodName: "GetIdentitiesByIdentity",
			Handler:    _UserService_GetIdentitiesByIdentity_Handler,
		},
		{
			MethodName: "GetIdentityByType",
			Handler:    _UserService_GetIdentityByType_Handler,
		},
		{
			MethodName: "AddIdentity",
			Handler:    _UserService_AddIdentity_Handler,
		},
		{
			MethodName: "GetPasswordCredential",
			Handler:    _UserService_GetPasswordCredential_Handler,
		},
		{
			MethodName: "CreateCredential",
			Handler:    _UserService_CreateCredential_Handler,
		},
		{
			MethodName: "GetCredentialByID",
			Handler:    _UserService_GetCredentialByID_Handler,
		},
		{
			MethodName: "GetUserCredentials",
			Handler:    _UserService_GetUserCredentials_Handler,
		},
		{
			MethodName: "GetUserCredentialsByType",
			Handler:    _UserService_GetUserCredentialsByType_Handler,
		},
		{
			MethodName: "PatchCredential",
			Handler:    _UserService_PatchCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _UserService_DeleteCredential_Handler,
		},
		{
			MethodName: "DeleteUserCredentialsByType",
			Handler:    _UserService_DeleteUserCredentialsByType_Handler,
		},
		{
			MethodName: "GetOpenIDByCredentialID",
			Handler:    _UserService_GetOpenIDByCredentialID_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _UserService_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _UserService_GetGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _UserService_ListGroups_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _UserService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _UserService_DeleteGroup_Handler,
		},
		{
			MethodName: "SetGroupMembers",
			Handler:    _UserService_SetGroupMembers_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _UserService_GetGroupMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/user.proto",
}
